from park import Park

# ISSUE WITH PARK 33

# Initialize the list of parks
acadia = Park('Acadia', 35, False)
american_samoa = Park('American Samoa', 9, False)
arches = Park('Arches', 36, False)
badlands = Park('Badlands', 40, False)
big_bend = Park('Big Bend', 23, False)
biscayne = Park('Biscayne', 24, False)
black_canyon = Park('Black Canyon of the Gunnison', 37, False)
bryce_canyon = Park('Bryce Canyon', 38, False)
canyonlands = Park('Canyonlands', 27, False)
capitol_reef = Park('Capitol Reef', 47, False)
carlsbad_caverns = Park('Carlsbad Caverns', 31, False)
channel_islands = Park('Channel Islands', 17, False)
conagree = Park('Conagree', 45, False)
crater_lake = Park('Crater Lake', 53, False)
cuyahoga_valley = Park('Cuyahoga Valley', 44, True)
death_valley = Park('Death Valley', 34, True)
denali = Park('Denali', 10, False)
dry_tortugas = Park('Dry Tortugas', 32, False)
everglades =Park('Everglades', 4, False)
gates_of_the_artic = Park('Gates of Arctic', 20, False)
glacier = Park('Glacier', 41, False)
glacier_bay = Park('Glacier Bay', 18, False)
grand_canyon = Park('Grand Canyon', 42, True)
grand_teton = Park('Grand Teton', 55, False)
great_basin = Park('Great Basin', 48, False)
great_sand_dunes = Park('Great Sand Dunes', 39, False)
great_smokey_mountains = Park('Great Smokey Mountains', 15, False)
guadalupe_mountains = Park('Guadalupe Mountains', 14, False)
haleakala = Park('Haleakala', 7, False)
hawaii_volcanoes = Park('Hawaii Volcanoes', 8, False)
hot_springs = Park('Hot Springs', 11, False)
isle_royale = Park('Isle Royale', 58, False)
joshua_tree = Park('Joshua Tree', 22, True)
katamai = Park('Katamai', 2, False)
kenai_fjords = Park('Kenai Fjords', 5, False)
kings_canyon = Park('Kings Canyon', 46, False)
kobuk_valley = Park('Kobuk Valley', 16, False)
lake_clark = Park('Lake Clark', 3, False)
lassen_volcanic = Park('Lassen Volcanic', 54, False)
mammoth_cave = Park('Mammoth Cave', 21, False)
mesa_verde = Park('Mesa Verde', 19, False)
mount_rainer = Park('Mount Rainer', 57, True)
north_cascades = Park('North Cascades', 60, False)
olympic = Park('Olympic', 59, True)
petrified_forest = Park('Petrified Forest', 13, False)
pinnacles = Park('Pinnacles', 30, False)
redwood = Park('Redwood', 56, False)
rocky_mountain = Park('Rocky Mountain', 43, True)
saguaro = Park('Saguaro', 12, True)
sequoia = Park('Sequoia', 29, True)
shenandoah = Park('Shenandoah', 28, True)
theodore_roosevelt = Park('Theodore Roosevelt', 50, False)
virgin_islands = Park('Virgin Islands', 6, False)
voyageurs = Park('Voyageurs', 49, False)
wind_cave = Park('Wind Cave', 52, False)
wrangell_st_elias = Park('Wrangell-St. Elias', 1, False)
yellowstone = Park('Yellowstone', 51, False)
yosemite = Park('Yosemite', 25, True)
zion = Park('Zion', 26, True)

